### ISSUE TITLE
Get elapsed time after the text has finished reading

### ISSUE THREAD

**Issue by alfaben12** [Marak/say.js#101]
How to get elapsed time after the text has finished reading, if in web we can used event onend.

Does says.js have an onend event?
thank you

**Comment by tlhunter** [comment]
You can store the time when you call the speech method, then compare the time in the callback with the original value.

```js
const start = Date.now()
say.speak("What's up, dog?", 'Good News', 1.0, (err) => {
  const duration = Date.now() - start
  if (err) {
    return console.error(err)
  }

  console.log(`Text tool ${duration}ms to be spoken`)
});
```

**Comment by alfaben12** [comment]
Cool, thanks
I look get a time including code executing
