### ISSUE TITLE
Does say.export work for Linux?

### ISSUE THREAD

**Issue by idoor88** [Marak/say.js#103]
Hi I saw there is a PR already years ago to make say.export to work for Linux, but in the document, it still says say.export is not supported for Linux platform? is it difficult to make it work for Linux? if I install Festival on linux, will the say.export() work on linux?

Thanks

**Comment by tlhunter** [comment]
`say.export` does not currently work on Linux. Installing festival is required to do anything on Linux.

The `text2wave` command may include some hints on how to get such functionality working in say.js.
