### ISSUE TITLE
Make speack function async and return a promise

### ISSUE THREAD

**Issue by oom-** [Marak/say.js#109]
Could you please just change the speack fonction by adding an async word front of it + return a new Promise ?
It would allow to use it like this: 

![image](https://user-images.githubusercontent.com/11071671/90935428-79ef9280-e403-11ea-91a3-86fa4230f9d4.png)

That's much better than to have the chain callback all time for every sentence.

Here is the pull request: https://github.com/Marak/say.js/pull/110

**Comment by tlhunter** [comment]
Duplicate of #69
