### ISSUE TITLE
No utf-8 encoding, unable to say languege specific letters 

### ISSUE THREAD

**Issue by Tymski** [Marak/say.js#115]
For example
When saying "Zażółć gęślą jaźń", polish letters will be skipped, even when explicitly setting a polish synthesizer.

**Comment by Teg3z** [comment]
Yeah, what encoding does it use?

**Comment by nandumoura** [comment]
yeah i have the same problem in latin characters like "ç ã õ á é" I change the encoding in the base file but dont work

**Comment by RandoMixs** [comment]
I have the same problem on Windows and this resolve utf 8 for me
#131

**Comment by Tymski** [comment]
Example solution that changes the encoding to utf-8 using exec and chcp:
```js
const { exec } = require('child_process');
const say = require('say');
exec('chcp 65001'); 
say.speak("Zażółć gęślą jaźń.", "Microsoft Paulina Desktop");
```

**Comment by Tymski** [comment]
> Yeah, what encoding does it use?

Turns out it uses encoding from the current console.
