### ISSUE TITLE
Add a method to set speech rate

### ISSUE THREAD

**Issue by tlhunter** [Marak/say.js#19]
The supported TTS engines allow configuration of speech rates. Abstract the differences into a simple floating point number (1.0 = normal).

say:

```
--rate=<WORDS PER MINUTE>
```

espeak:

```
-s <WORDS PER MINUTE=175>
```

**Comment by nowherenearithaca** [comment]
+1

It might be that '-r' sets rate in words per minute - in Darwin at least

 (https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/say.1.html).  Based on this so post (and my own informal experiments), default seems to be 175 -  http://apple.stackexchange.com/questions/96808/what-is-the-default-speaking-rate-for-the-speech-synthesis-program

**Comment by tlhunter** [comment]
Finalized in **v0.9.0**.
