### ISSUE TITLE
error on ubuntu/linux

### ISSUE THREAD

**Issue by chovy** [Marak/say.js#27]
```
SIOD ERROR: unbound variable : 
voice_welsh_hl
```

It doesn't matter which festival voice_ I use, i always get this error.

**Comment by digitalfrost** [comment]
I'm getting the same error on  Ubuntu  14.04 LTS

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

**Comment by digitalfrost** [comment]
Try the following
In Ubuntu Software Center look for **festvox** packages
There's quite a few: I'm installing **festvox-en1** and **festvox-us1** and seeing if this fixes the problem
