### ISSUE TITLE
Add a way to stop speaking

### ISSUE THREAD

**Issue by rbarman** [Marak/say.js#28]
It would be useful to be able to stop the speaker speaking or even have pause/resume abilities.

say.stop()
say.pause()
say.resume()

**Comment by anthonyettinger** [comment]
+1

**Comment by pehrlich** [comment]
+1

**Comment by Marcel-G** [comment]
+1

**Comment by pietrop** [comment]
+1

**Comment by angelxmoreno** [comment]
I feel like this would be a limitation of `say` or `festival`.

**Comment by tlhunter** [comment]
Stop is easy, we can simply kill the subprocess (say and festival seem to work that way).

Pausing and resuming is probably impossible, though I assume they aren't as important of a use-case.

**Comment by tlhunter** [comment]
Fixed in 8b2f87d9cd3a91bdfd3faa28bf82e6d34042a45b, available in `0.8.0`.

**Comment by tlhunter** [comment]
Please note that this is a breaking release which changes the `.speak()` arguments.

**Comment by angelxmoreno** [comment]
thanks @tlhunter !!
