### ISSUE TITLE
How to add voices

### ISSUE THREAD

**Issue by post2seth** [Marak/say.js#29]
Hello, i am quite beginner with the text to speech engine, but am interested to know as you are providing number of voices, is there any way we can add own voice, just similar to make a font? if its possible then how could be build. please give me a hint.

**Comment by derhuerst** [comment]
[As the Readme tells](blob/master/README.md), say.js uses the [system vioces](https://www.apple.com/accessibility/osx/voiceover/) on OS X and the [Felicitas voices](http://www.cstr.ed.ac.uk/projects/festival/morevoices.html) on Linux. Actually, say.js is not a speech engine, but leverages the OS speech engines.
