### ISSUE TITLE
Fix to Windows

### ISSUE THREAD

**Issue by LeandroFavero** [Marak/say.js#40]
Hi,

I couldn't open a Pull request, so for Windows is necessary to add this in first line:
var path = require('path');

And component will work perfectly.

**Comment by timdockins** [comment]
That's apparently been in index.js since April 12.  However, I still get "path is not defined".

**Comment by Sorashi** [comment]
@timdockins the npm package doesn't have it though, only the GitHub code has

**Comment by timdockins** [comment]
Yep.  Got it.  Thanks!

**Comment by derhuerst** [comment]
See #39.

**Comment by tlhunter** [comment]
This fix has been published to npm. Sorry for the slow turnaround.
