### ISSUE TITLE
Umlauts on german windows installation

### ISSUE THREAD

**Issue by hilderonny** [Marak/say.js#49]
Hi,

on german windows machines the PowerShell script you use expects an ISO-8859-1 console input. But the javascript output an UTF8 encoded string so that some umlauts like 'ä', 'ö', 'ü' are not spoken correctly.

You could fix this issues (maybe with other languages too?) by telling the PowerShell script to interpret the console input as UTF8 like so (line 64 in index.js):

```javascript
    commands = [ 'Add-Type -AssemblyName System.speech; $speak = New-Object System.Speech.Synthesis.SpeechSynthesizer; [Console]::InputEncoding = [System.Text.Encoding]::UTF8; $speak.Speak([Console]::In.ReadToEnd())' ];
```

Best regards, Ronny

**Comment by tlhunter** [comment]
Can you create a PR for this and confirm that it works exactly as expected?

**Comment by hilderonny** [comment]
Sorry, I am new to GitHub and have no experience in creating PR (Pull Requests?). But I downloaded the code, created a sample app as described in the README and changed the index.js in the way descibed above. Next I told the system to speak "Im Frühling wird es wärmer" (In spring it is getting warmer) where the "ä" sounds like the "a" in "jazz" and the "ü" sounds like the "u" in "turkey". Does this help you any further?

**Comment by svvac** [comment]
That fix seems to have been overwritten some time ago.

https://github.com/Marak/say.js/blob/master/platform/win32.js
