### ISSUE TITLE
Not have installed to my computer [windows7]

### ISSUE THREAD

**Issue by 4rcherry** [Marak/say.js#52]
`
c:\say>npm install say
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install" "say"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install say as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\say\npm-debug.log

c:\say>`

**Comment by big-kahuna-burger** [comment]
Your folder name is same as package name, and also your own package is called say. You can't install self with npm.
