### ISSUE TITLE
Cannot resolve module 'child_process'

### ISSUE THREAD

**Issue by SiriusED** [Marak/say.js#56]
I've installed your module and got this error in my Console:
Module not found: Error: Cannot resolve module 'child_process' in "My local directory path". But this module is on system directory of node.js, Why it looking in my local directory? What should I change to fix this issue?

**Comment by tlhunter** [comment]
What version of Node and NPM are you using? Which OS are you using? How did you install Node?

**Comment by SergioAA97** [comment]
Same issue here, 
Node : 6.11.0
npm : 5.0.4
OS : W 10 Home

Tried with both "npm install say" and "npm install say --save"

**Comment by tlhunter** [comment]
I'm unable to reproduce. The module itself is built into Node (https://nodejs.org/api/child_process.html). If I search for your error online I only ever see it related to Webpack. My only guess is that either Node is improperly installed or the module is being loaded in a non-Node environment. Either way I don't think there's anything I can do...
