### ISSUE TITLE
Not speed change on windows

### ISSUE THREAD

**Issue by mskogly** [Marak/say.js#65]
The speed setting doesn't seem to do anything on windows. Known issue?

console.log('Starting Sayjs');
say.speak("Daisy, Daisy, give me your answer do I'm half crazy all for the love of you, It won't be a stylish marriage, I can't afford a carriage , But you'll look sweet upon the seat, Of a bicycle built for two", 'Good News', 0.1, function(err) {
  if (err) {
    return console.error(err);
  }

  console.log('Text has been spoken.');
});

**Comment by tlhunter** [comment]
Yes, please see #46.
