### ISSUE TITLE
Mac OSX - Doesn't actually write the file using export()

### ISSUE THREAD

**Issue by neurofluxation** [Marak/say.js#77]
As per the title really. It plays the audio, when it finishes it says it has saved. But no file exits anywhere.

Code I have tried...

```
say.export("Welcome", 'Alex', 0.95, './hal.wav', (err) => {
      if (err) {
        return console.error(err)
      }
      console.info('Text has been saved to hal.wav.')
    })
```

```
say.export("Welcomee", 'Alex', 0.95, '~/nodejs-app/hal.wav', (err) => {
      if (err) {
        return console.error(err)
      }
      console.info('Text has been saved to hal.wav.')
    })
```

EDIT: It seems as though "Alex" isn't installed on Mac by default - It's using "Daniel" but not telling me.
Still doesn't work though...

**Comment by tlhunter** [comment]
I believe this was fixed in https://github.com/Marak/say.js/pull/74

**Comment by neurofluxation** [comment]
Hmm, doesn't seem to write for me. When I get a chance, I will run it up with full debugging and post here :)

**Comment by tlhunter** [comment]
Uh oh, specifically version `v0.15.0` doesn't allow exporting?

**Comment by princefishthrower** [comment]
For anyone checking in here in 2023... I could only get `export` to work by specifying the name "Daniel" and exporting to a .wav specifically - if you try a different name or exporting to something like `.mp3` it won't work (and won't throw any error either!)
