### ISSUE TITLE
error when trying to run demo

### ISSUE THREAD

**Issue by peterbarretto** [Marak/say.js#8]
I get the below error when i try to run the demo script:-
execvp(): No such file or directory

execvp(): No such file or directory

execvp(): No such file or directory

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: write EPIPE
    at errnoException (net.js:769:11)
    at Object.afterWrite (net.js:593:19)

**Comment by sgarns** [comment]
Having same issue as aferre. Worked locally, but not once I put it on a server. Any suggestions? Would be awesome to be able to use this module

**Comment by CodeOtter** [comment]
I do not have ```festival``` installed.

**Comment by tlhunter** [comment]
This should be fixed by installing Festival with a voice:

```shell
sudo apt-get install festival festvox-kallpc16k
```
