### ISSUE TITLE
getInstalledVoices returning null

### ISSUE THREAD

**Issue by Glutch** [Marak/say.js#91]
say.getInstalledVoices(voices => console.log(voices)) //null

say.speak('hello') works, and i have a lot of voices installed in "narrator settings"

windows 10

**Comment by Glutch** [comment]
Read somewhere that say.js grabs the selected narrator of the system. However if i change the narrator in windows settings (and i can hear that the voice change of course, with the narrator) - say.js still uses only one, the female Zira

**Comment by ajayyy** [comment]
You've got the wrong syntax, the callback returns two variables.

`say.getInstalledVoices((err, voices) => console.log(voices))`

**Comment by vitaly-t** [comment]
But this is how the latest version installs:

```ts
declare module 'say' {
  const say: SayJS.Say;

  namespace SayJS {
    type errorCallback = (err: string) => void;

    class Say {
      public export(text: string, voice?: string, speed?: number, filePath?: string, callback?: errorCallback): void;
      public speak(text: string, voice?: string, speed?: number, callback?: errorCallback): void;
      public stop(): void;
      public getInstalledVoices(callback: errorCallback): void;
    }
  }

  export = say;
}
```

So the whole TypeScript declaration is wrong.
